import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';


const data: InputData[] = [
    { label: 'A', value: 5 },
    { label: 'B', value: 10 },
    { label: 'C', value: 3 },
];
const chart = new Chartscii(data, {
    orientation: 'vertical',
    width: 80,
    padding: 1,
    barSize: 1,
    color: 'auto',
    theme: 'beach',
    alignBars: 'justify',
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    width: 720,
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/align-v-justify.svg', svg);
