import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';

const data = Array.from({ length: 10 }, (_, i) => i + 1);

const chart = new Chartscii(data, {
    orientation: 'vertical',
    title: {
        text: 'Aligned',
        align: 'center',
        padding: [2, 0],
        color: 'gradient',
    },
    width: 80,
    padding: 1,
    barSize: 1,
    sort: false,
    
    color: 'gradient(cyan, purple)',
    fill: '▒',
    fillColor: 'auto',
    theme: 'pastel',
    alignBars: 'justify',
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/align-title.svg', svg);
