import Chartscii from '../chartscii';
import shellfie from 'shellfie';
import { writeFileSync } from 'fs';

const data = Array.from({ length: 10 }, (_, i) => i + 1);
const chart = new Chartscii(data, {
    width: 50,
    theme: 'pastel',
    padding: 1,
    fillColor: 'auto',
    fill: '░',
    orientation: 'vertical',
    valueLabels: true,
    color: 'auto'
});

// console.log(chart.create());
const charts = chart.create();
const svg = shellfie(charts, {
    title: 'Auto Color',
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/auto-color.svg', svg);
