import Chartscii from '../chartscii';
import shellfie from 'shellfie';
import { writeFileSync } from 'fs';

const data = Array.from({ length: 10 }, (_, i) => i + 1);
const chart = new Chartscii(data, {
  width: 50,
  theme: 'pastel',
  barSize: 2,
  orientation: 'vertical',
  color: 'pink'
});

// console.log(chart.create());
const charts = chart.create();
const svg = shellfie(charts, {
    title: 'Basic',
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/basic.svg', svg);
