import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';

// 30 days of mock BTC/USD daily candles. [open, high, low, close]
// Values are made up but the sequence is plausible: a slow grind up,
// a sharp pullback near day 12, sideways consolidation with a doji,
// then a strong rally with one bearish reversal candle near the highs.
const month: InputData[] = [
    { value: [42100, 42850, 41800, 42600], label: '01' },
    { value: [42600, 43200, 42400, 43050], label: '02' },
    { value: [43050, 43400, 42700, 42900], label: '03' },
    { value: [42900, 43100, 42150, 42300], label: '04' },
    { value: [42300, 42950, 42100, 42850], label: '05' },
    { value: [42850, 43900, 42800, 43750], label: '06' },
    { value: [43750, 44200, 43500, 44100], label: '07' },
    { value: [44100, 44800, 44000, 44650], label: '08' },
    { value: [44650, 44900, 43800, 43950], label: '09' },
    { value: [43950, 44500, 43600, 44400], label: '10' },
    { value: [44400, 45200, 44300, 45050], label: '11' },
    { value: [45050, 45350, 42900, 43100], label: '12' },  // big bearish day
    { value: [43100, 43500, 42500, 42700], label: '13' },
    { value: [42700, 43200, 42400, 43150], label: '14' },
    { value: [43150, 43400, 42850, 42900], label: '15' },
    { value: [42900, 43500, 42850, 43450], label: '16' },
    { value: [43450, 43450, 43000, 43450], label: '17' },  // doji
    { value: [43450, 44100, 43300, 44050], label: '18' },
    { value: [44050, 44900, 43950, 44800], label: '19' },
    { value: [44800, 45600, 44700, 45500], label: '20' },
    { value: [45500, 46100, 45200, 46000], label: '21' },
    { value: [46000, 46800, 45800, 46700], label: '22' },
    { value: [46700, 47200, 46400, 47100], label: '23' },
    { value: [47100, 47900, 47000, 47800], label: '24' },
    { value: [47800, 48400, 47200, 47350], label: '25' },  // bearish reversal near highs
    { value: [47350, 47900, 47000, 47850], label: '26' },
    { value: [47850, 48600, 47750, 48500], label: '27' },
    { value: [48500, 49100, 48300, 49000], label: '28' },
    { value: [49000, 49500, 48700, 48900], label: '29' },
    { value: [48900, 49800, 48800, 49650], label: '30' },
];

const chart = new Chartscii(month, {
    type: 'candlestick',
    height: 18,
    color: 'auto',
    title: { text: 'BTC/USD — 30d', align: 'center', color: 'gradient' },
    legend: { position: 'top', align: 'right' },
});

console.log(chart.create());
const svg = shellfie(chart.create(), {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/candlestick.svg', svg);
