import { writeFileSync } from 'fs';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';
import shellfie from 'shellfie';


// generate random chart data
const data: InputData[] = [];

for (let i = 1; i <= 5; i++) {
    data.push({ value: i });
}

// create chart
const chart = new Chartscii(data, {
    orientation: 'vertical',
    barSize: 10,
    sort: false,
    fill: '▒',
    fillColor: 'auto',
    colorLabels: true,
    color: 'gradient(pink,cyan:reverse)',
    theme: 'pinkish',
    percentage: true,
    labels: true
});

console.log(chart.create())
const svg = shellfie(chart.create(), {
    title: 'Gradient reverse',
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/gradient-reverse.svg', svg);

