import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';

const data = Array.from({ length: 20 }, (_, i) => ({
    value: Math.round(Math.sin(i / 3) * 10 + 15),
    label: `${i}`
}));

const chart = new Chartscii(data, {
    width: 60,
    title: {
        text: 'Gradient Aligned Right',
        align: 'right',
        color: 'gradient',
    },
    orientation: 'vertical',
    color: 'gradient(pink,cyan)',
    theme: 'beach',
    fill: '░',
    padding: 1,
    fillColor: 'auto',
    valueLabels: true
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/gradient-right.svg', svg);
