import Chartscii from '../chartscii';
import shellfie from 'shellfie';
import { writeFileSync } from 'fs';

const data = Array.from({ length: 10 }, (_, i) => i + 1);
const chart = new Chartscii(data, {
    fill: '░',
    labelFormat: (label) => `\x1b[7mlabel ${label}`,
    fillColor: 'auto',
    padding: 1,
    theme: 'beach',
    valueLabels: true,
    orientation: 'vertical',
    color: 'gradient(lime,purple)'
});

// console.log(chart.create());
const charts = chart.create();
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/label-format.svg', svg);
