import { writeFileSync } from 'fs';
import { shellfie } from 'shellfie';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';

const data: InputData[][] = [];
const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
for (let i = 0; i < 12; i++) {
    const value = Math.floor(Math.random() * (40)) + 1;
    data.push([{ value, label: months[i] }]);
}

// create chart
const chart = new Chartscii(data, {
    type: 'line',
    width: 100,
    theme: 'pastel',
    color: 'green',
    fillColor: 'green',
    labels: false,
});


console.log(chart.create());
const svg = shellfie(chart.create(), {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/line.svg', svg);