import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';


const data: InputData[] = [
    { label: 'Jan', value: [2, 8] },
    { label: 'Feb', value: [1, 9] },
    { label: 'Mar', value: [3, 7] },
    { label: 'Apr', value: [6, 4] },
    { label: 'May', value: [3, 7] },
    { label: 'Jun', value: [9, 1] },
    { label: 'Jul', value: [4, 6] },
];
const chart = new Chartscii(data, {
    barSize: 2,
    width: 60,
    padding: 2,
    alignBars: 'justify',
    color: 'gradient(#72cac6,#CA7276)',
    valueLabels: true,
    valueLabelFormat: (values) => values.map(v => Number(v) / 10).join(' / '),
    stackColors: ['#72cac6', '#CA7276'],
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/stacked-format.svg', svg);
