import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';


const data: InputData[] = [
    { label: 'Mon', value: [5, 10, 5] },
    { label: 'Tue', value: [7, 3, 10] },
    { label: 'Wed', value: [10, 6, 4] },
    { label: 'Thu', value: [3, 6, 11], color: ['cyan', 'pink', 'purple'] },
    { label: 'Fri', value: [8, 6, 6] },
    { label: 'Sat', value: [11, 5, 6] },
    { label: 'Sun', value: [9, 6, 5] },
];
const chart = new Chartscii(data, {
    barSize: 2,
    width: 60,
    padding: 5,
    theme: 'pastel',
    alignBars: 'justify',
    orientation: 'vertical',
    color: 'auto',
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/stacked-override.svg', svg);
