import { writeFileSync } from 'fs';
import Chartscii from '../chartscii';
import { InputData } from '../types/types';
import { shellfie } from 'shellfie';

const data: InputData[] = [];
const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
for (let i = 0; i < 12; i++) {
    const value1 = Math.floor(Math.random() * (40)) + 1;
    data.push(value1);
}

// create chart
const chart = new Chartscii(data, {
    type: 'step',
    width: 100,
    theme: 'pastel',
    variant: 'smooth', // 'smooth' (╭╮╰╯) or 'sharp' (/\)
    color: 'green',
    pointChar: '◈',
    points: true,
    legend: true
});

console.log(chart.create());
const svg = shellfie(chart.create(), {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync
('examples/svgs/step-point.svg', svg);
