import { writeFileSync } from 'fs';
import shellfie from 'shellfie';
import Chartscii from '../chartscii';

const data = [
  { value: 10, label: '*bold* Sales', color: 'green' },
  { value: 5, label: '%italic% Returns', color: 'red' },
  { value: 8, label: '!underline! Pending', color: 'yellow' },
  { value: 3, label: '@invert@ Cancelled', color: 'purple' }
];

const chart = new Chartscii(data, {
    barSize: 16,
    theme: 'pastel',
    alignBars: 'justify',
    orientation: 'vertical',
    stackColors: ['red', 'orange', 'yellow'],
});

const charts = chart.create();
console.log(charts);
const svg = shellfie(charts, {
    watermark: '\x1b[0;2mGenerated by shellfie',
})
writeFileSync('examples/svgs/styl3.svg', svg);


