name: docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: cp readme
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          rm docs/README.md
          cp README.md docs/
          git add .
          git commit -a -m "updating docs 📚"
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}